### ISSUE TITLE
Create ClusterLink website

### ISSUE THREAD

**Issue by michalmalka** [clusterlink-net/clusterlink#106]
- [x] Decide on contents (landing page, docs, tutorials, ...)
- [x] Hosting for the website (Netlify, GitHub pages?)

Options for website platform (e.g., MkDocs, Hugo, Jekyll)

**Comment by elevran** [comment]
Settling on using Hugo with Docsy theme. [Examples](https://www.docsy.dev/docs/examples/) seem close to what we need.
Hosting can be automated via Netlify - lots of documentation, including on moving to our own domain.

Considering following Sections to include:
- landing page (mostly logo, one liner of what it is and notable features?)
- About
- User documentation (reference, guides and tutorials) (see [Diataxis framework](https://diataxis.fr/) for discussion of documentation)
- Development (or part of documentation?)
- Blog

Considered GH pages but this seems to be a little more complicated ("... typically built in a separate branch of the project, can become confusing with time. Less freedom to customize...").
See https://dev.to/erikaheidi/setting-up-a-documentation-website-for-your-software-project-with-hugo-and-netlify-4bpj

**Comment by elevran** [comment]
#199 has a complete website preview.
Site is auto-published as https://stunning-daffodil-b10f6b.netlify.app/ for now, will be rerouted to clusterlink.net domain.
The major remaining tasks will be tracked as separate issues:
- complete pages (landing, documentation, about)
- website look and feel (need volunteers with prior knowledge - my design skills are non-existent 🙃)
- setting up
