### ISSUE TITLE
Reorg packages, directories and files under pkg/policyengine

### ISSUE THREAD

**Issue by zivnevo** [clusterlink-net/clusterlink#20]
Suggestion from @ORO :

* `pkg/policyEngine` -> `pkg/policy` [maybe this is orthogonal to this PR, as this package already exists today]
* `connectivity_pdp.go` -> `pkg/policy/connectivity/pdp.go` 
* `policytypes/connectivity_policy.go` -> `pkg/policy/connectivity/types.go` 
* `connectivity_policy_crd.go` -> `pkg/api/policy/types.go`
* The conversion (`NativePolicy()`) from user-facing types (which are under `pkg/api`) and the internal types (which are under `pkg/policy/types.go`) should not be inside the pkg/api, but moved in the server that accepts this API, i.e. `pkg/server/policy/server.go`.
* move all `policyTier` code to `pkg/policy/tier.go` and make it work on a generic policy interface (not just connectivity policies).
* make PDP generic as well and place in `pkg/policy/pdp.go`
* drop `connectivity` prefix from types defined in `pkg/policy/connectivity/` (e.g. `ConnectivityPolicy` -> `Policy`).
* drop all "policy" prefixes from names defined under `pkg/policy`.

In addition, summarize all exported PDP methods in one interface.
Also, avoid duplication between `api.Policy` and `ConnectivityPolicy`

**Comment by elevran** [comment]
@zivnevo still ongoing or done?

**Comment by zivnevo** [comment]
Some items were already addressed, others will be addressed when we have a controller+CRDs for policies.
