### ISSUE TITLE
Issue with heartbeat mechanism not using certificate correctly

### ISSUE THREAD

**Issue by elevran** [clusterlink-net/clusterlink#23]
I'm trying to make use of dynamically generated x509 certificates instead of the statically generated certificates. However, I'm having the following error messages in the controlplane component:

```
/tmp # /controlplane get log
ERROR  [2023-09-11 15:31:17] Unable to send heartbeat to https://172.18.0.3:30443/hb, Error: Post "https://172.18.0.3:30443/hb": x509: certificate is valid for gwctl2, mbg2, localhost, not mbg1  component=controlPlane/health file=/gw/pkg/controlplane/health/healthMonitor.go line=77
ERROR  [2023-09-11 15:31:18] Unable to send heartbeat to https://172.18.0.3:30443/hb, Error: Post "https://172.18.0.3:30443/hb": x509: certificate is valid for gwctl2, mbg2, localhost, not mbg1  component=controlPlane/health file=/gw/pkg/controlplane/health/healthMonitor.go line=77
ERROR  [2023-09-11 15:31:19] Unable to send heartbeat to https://172.18.0.3:30443/hb, Error: Post "https://172.18.0.3:30443/hb": x509: certificate is valid for gwctl2, mbg2, localhost, not mbg1  component=controlPlane/health file=/gw/pkg/controlplane/health/healthMonitor.go line=77
```

This is the controlplane on mbg1. From the error message, it seems mbg1 is sending heartbeats to mbg2 and expecting mbg2 to send a certificate with mbg1 in the SAN field. This seems there's a bug.

I discussed the issue with @kfirtoledo, and he suggested that I encode mbg1's cert to also include mbg2 in the SAN field, and the same in mbg2's cert to include mbg1 in its SAN field. This resolved the problem, and everything works again.

**Comment by elevran** [comment]
@kfirtoledo - is this still relevant following the changes to CP and DP?
Can you assess and document status?

**Comment by kfirtoledo** [comment]
It should be resolved in the new controlplane
