### ISSUE TITLE
CLI harmonization and enhancements

### ISSUE THREAD

**Issue by elevran** [clusterlink-net/clusterlink#25]
CLI should be made consistent in terms of
- concepts exposed to the user
- parameter names
- use of CRUD style (similar to kubectl) etc

Enhancements:
- saving state so calls are easier (e.g., using kubeconfig/context)
- logging
- utility CLIs to help UX/automation (e.g., creating ingress/nodeport YAML for a new gateway, generating GW config including Pod, ServiceAccount, RBAC on per namespace or cluster scope, etc)

**Comment by michalmalka** [comment]
Not relevant anymore
