### ISSUE TITLE
Policies to control export and import

### ISSUE THREAD

**Issue by zivnevo** [clusterlink-net/clusterlink#290]
We can either
* Define dedicated policies to control which services to export and import OR
* Derive permission from the existing access policies

**Comment by elevran** [comment]
@zivnevo what's the status of this one? Still needed with privileged/unprivileged and import/export CRDs?

**Comment by zivnevo** [comment]
> @zivnevo what's the status of this one? Still needed with privileged/unprivileged and import/export CRDs?

I'm not sure we still need it, at least not until we have a management plane and UI. It's something that existed in the (very) old code, before I joined, so someone might still have feelings towards it.

**Comment by elevran** [comment]
So closing it for now and can reopen if and when it comes up again.
