### ISSUE TITLE
New controlplane missing features

### ISSUE THREAD

**Issue by orozery** [clusterlink-net/clusterlink#39]
A list of features which exist in the current controlplane, and missing on the newer one:
- [x] Create k8s service for imports
- [x] Create k8s service for export (Export.Spec.ExternalService)
- [x] Connectivity policies
- [x] Legacy policies? (ACL / LB)
- [x] #45
~~- [ ] Metrics collection~~
- [x] Heartbeat
~~- [ ] Support plaintext connections (in addition to mTLS which is already supported) ? (Is this needed?)~~

**Comment by elevran** [comment]
@orozery can you please review status of items and mark/close accordingly?
