### ISSUE TITLE
Support binding services in different namespaces

### ISSUE THREAD

**Issue by kfirtoledo** [clusterlink-net/clusterlink#40]
When doing add import we should support the creation of a new k8s service in different namespaces.

**Comment by elevran** [comment]
not sure if we want to support that. Conceptually, why would you be allowed to expose someone else's service? Seems to breach isolation and namespace boundaries. As a user you might still be able to do so with a local ExternalName service referring to another Service, but not sure we should support this explicitly. Or we can validate the the Export always refers to a service of type ClusterIP

**Comment by kfirtoledo** [comment]
It will be supported by default in the CRD mode, the ClusterLink system will be in a different namespace.

**Comment by elevran** [comment]
@kfirtoledo I think the CRD mode should still validate that the `Export` refers to a service in the same namespace it is defined in.
