### ISSUE TITLE
[website]: Consider using only MAJOR.MINOR in documentation versions (i.e., `v0.1` not `v0.1.0`)

### ISSUE THREAD

**Issue by elevran** [clusterlink-net/clusterlink#539]
Should we use vX.Y only in version numbers? Patch level releases should not affect API documentation.
If this is decided, it would be best to do so as early as possible and rename released versions accordingly (e.g., `v0.1.0` to `v0.1`)

**Comment by michalmalka** [comment]
Let's use only major.minor starting from next release 0.2
