### ISSUE TITLE
[BUG]: Connection timeout in bookinfo tutorial

### ISSUE THREAD

**Issue by welisheva22** [clusterlink-net/clusterlink#602]
**Describe the bug**
Connection timeout for bookinfo tutorial when viewing product page

**To Reproduce**
1. I followed the bookinfo tutorial line by line and received no error messages on the command line until:
2. When trying to view the product page from Firefox I got the following error message:
![Connection time out error](https://github.com/clusterlink-net/clusterlink/assets/169834950/244c1361-e00a-4985-909f-e0ae7dd0eb61)
3. Out of curiosity I tried looking at the page from Safari and got a similar message (connection timeout)

**Expected behavior**
I would have expected to see a web page similar to the client image at the top of the tutorial (Cluster 1)

**Additional context**
clusterlink version v0.2.1-rev-f69da3b-dirty
Here is a picture from Docker Desktop showing the containers:
![Docker desktop containers](https://github.com/clusterlink-net/clusterlink/assets/169834950/54b263b6-e6b0-4718-b369-4f25be7c5f36)
Docker desktop images:
![Docker desktop images](https://github.com/clusterlink-net/clusterlink/assets/169834950/ee6cd583-deff-4d18-9099-12795e4b01bd)
Docker desktop volumes:
![Docker desktop volumes](https://github.com/clusterlink-net/clusterlink/assets/169834950/216065b2-9033-402b-b092-3956f0da9b31)
Information about the first volume (related to the client):
![volume 1 details a](https://github.com/clusterlink-net/clusterlink/assets/169834950/15c914d5-d037-47ca-81a2-1227b78a1972)
![volume 1 details b](https://github.com/clusterlink-net/clusterlink/assets/169834950/ca195f95-8603-4e69-8202-61ca22764b97)

Could we add some documentation about triaging this problem in case it occurs for others?
Has anyone else been able to reproduce this problem?

**Comment by welisheva22** [comment]
Hi-- perhaps this is out of scope, we did the tutorial together again on my Mac and things seemed to run smoothly in setup, even if we still did not succeed to see the product page from a web browser.
We used this to try to see it in Firefox:
open -a "Firefox" http://$CLIENT_IP:30001/productpage
It lagged for a long time
no output


However, after this command:
kubectl describe peers.clusterlink.net -A
we did received the message:
Status:
  Conditions:
    Last Transition Time:  2024-07-31T07:28:00Z
    Message:               
    Reason:                Heartbeat
    Status:                True
    Type:                  PeerReachable

**Comment by kfirtoledo** [comment]
The tutorial is working fine and tested again on v0.4. This issue is more related to how you can connect from the web browser to the application on Mac (in this case Istio product page service). 
This is out of the scope of ClusterLink.
