### ISSUE TITLE
Design of ClusterLink logo

### ISSUE THREAD

**Issue by elevran** [clusterlink-net/clusterlink#83]

**Comment by andreagreggo2** [comment]
![CL 2 dark](https://github.com/clusterlink-net/clusterlink/assets/61422905/5492418a-ef85-4f14-afc5-46230af5084b)
![CL 2 light](https://github.com/clusterlink-net/clusterlink/assets/61422905/ee03c23b-4897-4285-a3bc-0f86db516902)
Take a look at these and let me know what you think. I tried to simplify them a little bit.

**Comment by michalmalka** [comment]
I liked better your first version (which is asymmetric) 
![image](https://github.com/clusterlink-net/clusterlink/assets/25298711/9737428c-09c1-4944-8929-bc2aac7a86e4)
